# Generated by Django 5.2.12 on 2026-03-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Indian/Antananarivo', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='workspace_label',
            field=models.CharField(blank=True, default='Mon Workspace', max_length=255),
        ),
    ]
