# Generated by Django 5.2.12 on 2026-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactrequest_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_exp_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_exp_year',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
