# Generated by Django 5.2.9 on 2026-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscription_card_brand_subscription_card_exp_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='master_api_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
