# Generated by Django 5.2.12 on 2026-03-30 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('viewer', 'Lecteur'), ('editor', 'Éditeur')], default='viewer', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('viewer', 'Lecteur'), ('editor', 'Éditeur')], default='viewer', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_of', to=settings.AUTH_USER_MODEL)),
                ('workspace_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre du workspace',
                'verbose_name_plural': 'Membres du workspace',
                'unique_together': {('workspace_owner', 'member_email')},
            },
        ),
    ]
