# Generated by Django 5.2.12 on 2026-03-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_workspaceinvitation_workspacemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workspace_label',
            field=models.CharField(blank=True, default='Mon espace de travail', max_length=255),
        ),
    ]
