# Generated by Django 5.2.12 on 2026-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_subscription_active_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gateway_customer_id',
            field=models.CharField(blank=True, help_text='ID client Stripe', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gateway_subscription_id',
            field=models.CharField(blank=True, help_text='ID abonnement Stripe', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
