# Generated by Django 5.2.12 on 2026-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_paymenttransaction_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enterprise_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
