# Generated by Django 5.2.12 on 2026-03-23 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=255)),
                ('system_prompt', models.TextField()),
                ('llm_model', models.CharField(default='GPT-4o', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('channels', models.JSONField(default=list)),
                ('execution_mode', models.CharField(choices=[('suggest', 'Suggest'), ('auto', 'Auto (threshold)'), ('full_auto', 'Full Auto')], max_length=50)),
                ('confidence_threshold', models.IntegerField(default=85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deployed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Email', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('imap_server', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_server', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('vertical', models.CharField(max_length=100)),
                ('default_role', models.CharField(max_length=255)),
                ('default_channels', models.JSONField(default=list)),
                ('default_autonomy', models.CharField(default='Auto 85%', max_length=50)),
                ('estimated_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default WhatsApp', max_length=255)),
                ('is_connected', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(default='chat', max_length=50)),
                ('content', models.TextField()),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='email_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.emailconfig'),
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=100)),
                ('file_binary', models.BinaryField(blank=True, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('raw_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='agents.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='whatsapp_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.whatsappconfig'),
        ),
    ]
