# Generated by Django 5.2.9 on 2026-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_user_emailconfig_user_whatsappconfig_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pertinent', 'Pertinent'), ('archived', 'Archived')], default='new', max_length=50),
        ),
    ]
