# Generated by Django 5.2.9 on 2026-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_chatmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
