# Generated by Django 5.2.12 on 2026-03-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_chatmessage_user_alter_chatmessage_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
