# Generated by Django 5.2.12 on 2026-04-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentfeedback_usersurvey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='raw_content',
        ),
    ]
