# Generated by Django 5.2.12 on 2026-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agentlink_agentteam_agent_team_contactassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentteam',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentteam',
            name='color',
            field=models.CharField(default='#1e3a8a', max_length=20),
        ),
    ]
