# Generated by Django 5.2.12 on 2026-04-13 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_agent_is_team_agent_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='email_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.emailconfig'),
        ),
    ]
