# Generated by Django 5.2.12 on 2026-04-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_chatmessage_email_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
