# Generated by Django 5.2.12 on 2026-05-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_linkedinconfig_agent_linkedin_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinconfig',
            name='is_messaging_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkedinconfig',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinconfig',
            name='li_at_cookie',
            field=models.TextField(blank=True, help_text='LinkedIn Session Cookie (li_at)', null=True),
        ),
    ]
