# Generated by Django 5.2.12 on 2026-05-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_linkedinconfig_is_messaging_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinconfig',
            name='unipile_account_id',
            field=models.CharField(blank=True, help_text='ID du compte Unipile', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkedinconfig',
            name='li_at_cookie',
            field=models.TextField(blank=True, help_text='LinkedIn Session Cookie (fallback)', null=True),
        ),
    ]
