# Generated by Django 5.2.12 on 2026-05-11 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_linkedinconfig_unipile_account_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='unipile_account_id',
            field=models.CharField(blank=True, help_text='ID du compte Unipile', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='unipile_account_id',
            field=models.CharField(blank=True, help_text='ID du compte Unipile', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FacebookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Facebook', max_length=255)),
                ('is_connected', models.BooleanField(default=False)),
                ('unipile_account_id', models.CharField(blank=True, help_text='ID du compte Unipile', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='facebook_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.facebookconfig'),
        ),
    ]
