# Generated by Django 5.2.12 on 2026-05-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_emailconfig_unipile_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='followup_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='next_followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='replied_since_last_ai',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau / 1er Contact'), ('contacted', 'Contacté'), ('interested', 'Intéressé'), ('ready', 'Prêt'), ('no', 'Non intéressé')], default='new', max_length=20),
        ),
    ]
