# Generated by Django 5.2.12 on 2026-05-18 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_contact_followup_count_contact_next_followup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='agents.agentteam'),
        ),
    ]
