# Generated by Django 5.2.12 on 2026-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_knowledgebase_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, help_text='Besoins ou informations sur le prospect', null=True),
        ),
    ]
