# Generated by Django 5.2.12 on 2026-06-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_add_notes_to_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookconfig',
            name='page_access_token',
            field=models.TextField(blank=True, help_text="Token d'accès de la Page Facebook", null=True),
        ),
        migrations.AddField(
            model_name='facebookconfig',
            name='page_id',
            field=models.CharField(blank=True, help_text='ID de la Page Facebook', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facebookconfig',
            name='page_name',
            field=models.CharField(blank=True, help_text='Nom de la Page Facebook', max_length=255, null=True),
        ),
    ]
