# Generated by Django 5.2.12 on 2026-07-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0024_prospect_search_apollo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectlead',
            name='contact_fb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apollo_fb_leads', to='agents.contact'),
        ),
        migrations.AddField(
            model_name='prospectlead',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='prospectsearchjob',
            name='channels',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('both', 'Email + WhatsApp'), ('all', 'Email + WhatsApp + Facebook')], default='both', max_length=20),
        ),
    ]
