# Generated by Django 5.2.12 on 2026-07-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0025_prospectlead_contact_fb_prospectlead_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agentteam',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='name',
            field=models.CharField(default='Nouveau Email', max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='name',
            field=models.CharField(default='Nouveau WhatsApp', max_length=255),
        ),
    ]
